cleanup_default_locations: true
email: postgres-team+dev@clickhouse.com
enabled: true
locations:
  - account_name: dev-us-west-2-cell0-clickgres
    name: us-west-2-cell-0
    region: us-west-2
    role: arn:aws:iam::423535493707:role/ClickgresCellManagementAccessRole
    dns_suffix: c0.us-west-2
  - account_name: dev-us-east-1-cell0-clickgres
    name: us-east-1-cell-0
    region: us-east-1
    role: arn:aws:iam::069372914117:role/ClickgresCellManagementAccessRole
    dns_suffix: c0.us-east-1
dns_server_amis:
  us-west-2:
    arch_x64: ami-053ee446a8202ddd8
    arch_arm64: ami-0b9a0e4bd28ad4afe
  us-east-1:
    arch_x64: ami-03deb8c961063af8c
    arch_arm64: ami-0a105b59f5c9471cb
password: PASSWORD_TEST
project_name: clickgres-development
project_uuid: 3fa904f0-e4dc-86d2-a919-f8b0a326206f
